# -*- coding: utf-8 -*-
"""crawler_platform 静态任务清单。

本文件由 `python scripts/sync_sch.py --write` 根据 /spiders 下的 TASK_DEFINITION/TASKS 生成。
平台接入脚本会用 ast.literal_eval 静态解析 TASKS，因此本文件必须保持纯静态字面量。
新增平台爬虫时，只在 /spiders 或 /open_api 中增加业务代码，然后运行 sync_sch.py 生成本文件。
"""

TASKS = [{'definitionKey': 'demo_async_echo',
  'taskName': '示例异步回显任务',
  'defaultParams': {'text': 'async'},
  'suggestedCron': '',
  'executionMode': 'SINGLE',
  'idempotencyPolicy': 'IDEMPOTENT',
  'resourceRequirements': {},
  'requiredCapabilities': {'browser': False},
  'runtimeMode': 'SHARED_ENV_ISOLATED',
  'taskGroup': 'demo',
  'taskMaxConcurrency': 1,
  'groupMaxConcurrency': 4,
  'exclusiveMode': False,
  'ioClass': 'LOW',
  'shmSizeMb': 64,
  'logLimitMb': 20,
  'resourceLocks': [],
  'secretRefs': [],
  'allowOfflineRun': False,
  'offlinePolicy': {},
  'entryModule': 'spiders.demo.async_echo',
  'entryFunction': 'run',
  'sourceFile': 'spiders/demo/async_echo.py',
  'platformCode': 'demo',
  'requiredConfigs': [],
  'requiredCredentials': [],
  'outputTables': [],
  'contractVersion': '1'},
 {'definitionKey': 'demo_echo',
  'taskName': '示例回显任务',
  'defaultParams': {'text': 'hello'},
  'suggestedCron': '',
  'executionMode': 'SINGLE',
  'idempotencyPolicy': 'IDEMPOTENT',
  'resourceRequirements': {},
  'requiredCapabilities': {'browser': False},
  'runtimeMode': 'SHARED_ENV_ISOLATED',
  'taskGroup': 'demo',
  'taskMaxConcurrency': 1,
  'groupMaxConcurrency': 4,
  'exclusiveMode': False,
  'ioClass': 'LOW',
  'shmSizeMb': 64,
  'logLimitMb': 20,
  'resourceLocks': [],
  'secretRefs': [],
  'allowOfflineRun': False,
  'offlinePolicy': {},
  'entryModule': 'spiders.demo.echo',
  'entryFunction': 'run',
  'sourceFile': 'spiders/demo/echo.py',
  'platformCode': 'demo',
  'requiredConfigs': [],
  'requiredCredentials': [],
  'outputTables': [],
  'contractVersion': '1'},
 {'definitionKey': 'jdd_items_sync',
  'taskName': '京多多现货商品采集',
  'defaultParams': {'pageSize': 500,
                    'pageNum': 1,
                    'dryRun': False,
                    'verifyTls': False,
                    'keyword': '',
                    'cities': '',
                    'categoryId': ''},
  'suggestedCron': '',
  'executionMode': 'SINGLE',
  'idempotencyPolicy': 'IDEMPOTENT',
  'resourceRequirements': {},
  'requiredCapabilities': {'browser': False},
  'runtimeMode': 'SHARED_ENV_ISOLATED',
  'taskGroup': 'jdd',
  'taskMaxConcurrency': 1,
  'groupMaxConcurrency': 2,
  'exclusiveMode': False,
  'ioClass': 'NORMAL',
  'shmSizeMb': 64,
  'logLimitMb': 50,
  'resourceLocks': [],
  'secretRefs': [],
  'allowOfflineRun': False,
  'offlinePolicy': {},
  'requiredConfigs': [{'slot': 'mongo_jdd',
                       'type': 'MONGO',
                       'description': '京多多商品结果库 MongoDB，由 crawler_platform 公司资源配置绑定并在运行时下发。',
                       'required': True}],
  'requiredCredentials': [],
  'outputTables': [{'slot': 'items',
                    'defaultName': 'jdd.items',
                    'writeMethod': 'upsert',
                    'description': '京多多现货商品采集结果，唯一键 item_id。'}],
  'entryModule': 'spiders.jdd.items',
  'entryFunction': 'run',
  'sourceFile': 'spiders/jdd/items.py',
  'platformCode': 'jdd',
  'contractVersion': '1'},
 {'definitionKey': 'oilchem_login_check',
  'taskName': '隆众资讯登录校验',
  'defaultParams': {'username': '',
                    'password': '',
                    'token': '',
                    'cookieString': '',
                    'cookieSecretRef': '',
                    'credentialKey': 'oilchem_main',
                    'captchaValidate': '',
                    'captchaId': 'a17cc715e78a4afc8c43cd85da9d7254',
                    'target': 'https://dc.oilchem.net/page/#/index',
                    'check': True,
                    'persist': True},
  'suggestedCron': '',
  'executionMode': 'SINGLE',
  'idempotencyPolicy': 'IDEMPOTENT',
  'resourceRequirements': {},
  'requiredCapabilities': {'browser': False},
  'runtimeMode': 'SHARED_ENV_ISOLATED',
  'taskGroup': 'oilchem',
  'taskMaxConcurrency': 1,
  'groupMaxConcurrency': 2,
  'exclusiveMode': False,
  'ioClass': 'NORMAL',
  'shmSizeMb': 64,
  'logLimitMb': 20,
  'resourceLocks': [],
  'secretRefs': ['oilchem_account'],
  'allowOfflineRun': False,
  'offlinePolicy': {'maxOfflineHours': 0, 'reason': '登录校验默认不离线执行，避免 cookie 失效时重复请求。'},
  'entryModule': 'spiders.oilchem.login',
  'entryFunction': 'run',
  'sourceFile': 'spiders/oilchem/login.py',
  'platformCode': 'oilchem',
  'requiredConfigs': [],
  'requiredCredentials': [],
  'outputTables': [],
  'contractVersion': '1'},
 {'definitionKey': 'system_health',
  'taskName': '系统健康检查',
  'defaultParams': {'message': 'health check passed'},
  'suggestedCron': '',
  'executionMode': 'SINGLE',
  'idempotencyPolicy': 'IDEMPOTENT',
  'resourceRequirements': {},
  'requiredCapabilities': {'browser': False},
  'runtimeMode': 'SHARED_ENV_ISOLATED',
  'taskGroup': 'system',
  'taskMaxConcurrency': 1,
  'groupMaxConcurrency': 4,
  'exclusiveMode': False,
  'ioClass': 'LOW',
  'shmSizeMb': 64,
  'logLimitMb': 20,
  'resourceLocks': [],
  'secretRefs': [],
  'allowOfflineRun': False,
  'offlinePolicy': {},
  'entryModule': 'spiders.system.health',
  'entryFunction': 'run',
  'sourceFile': 'spiders/system/health.py',
  'platformCode': 'system',
  'requiredConfigs': [],
  'requiredCredentials': [],
  'outputTables': [],
  'contractVersion': '1'}]
