# -*- coding: utf-8 -*-
"""crawler_platform 静态任务清单。

本文件由 `python scripts/sync_sch.py --write` 根据 /spiders 下的 TASK_DEFINITION/TASKS 生成。
平台接入脚本会用 ast.literal_eval 静态解析 TASKS，因此本文件必须保持纯静态字面量。
新增平台爬虫时，只在 /spiders 或 /open_api 中增加业务代码，然后运行 sync_sch.py 生成本文件。
"""

TASKS = [{'definitionKey': 'demo_async_echo',
  'taskName': '示例异步回显任务',
  'defaultParams': {'text': 'async'},
  'suggestedCron': '',
  'executionMode': 'SINGLE',
  'idempotencyPolicy': 'IDEMPOTENT',
  'resourceRequirements': {},
  'requiredCapabilities': {'browser': False},
  'runtimeMode': 'SHARED_ENV_ISOLATED',
  'taskGroup': 'demo',
  'taskMaxConcurrency': 1,
  'groupMaxConcurrency': 4,
  'exclusiveMode': False,
  'ioClass': 'LOW',
  'shmSizeMb': 64,
  'logLimitMb': 20,
  'resourceLocks': [],
  'secretRefs': [],
  'entryModule': 'spiders.demo.async_echo',
  'entryFunction': 'run',
  'sourceFile': 'spiders/demo/async_echo.py'},
 {'definitionKey': 'demo_echo',
  'taskName': '示例回显任务',
  'defaultParams': {'text': 'hello'},
  'suggestedCron': '',
  'executionMode': 'SINGLE',
  'idempotencyPolicy': 'IDEMPOTENT',
  'resourceRequirements': {},
  'requiredCapabilities': {'browser': False},
  'runtimeMode': 'SHARED_ENV_ISOLATED',
  'taskGroup': 'demo',
  'taskMaxConcurrency': 1,
  'groupMaxConcurrency': 4,
  'exclusiveMode': False,
  'ioClass': 'LOW',
  'shmSizeMb': 64,
  'logLimitMb': 20,
  'resourceLocks': [],
  'secretRefs': [],
  'entryModule': 'spiders.demo.echo',
  'entryFunction': 'run',
  'sourceFile': 'spiders/demo/echo.py'},
 {'definitionKey': 'oilchem_login_check',
  'taskName': '隆众资讯登录校验',
  'defaultParams': {'username': '',
                    'password': '',
                    'token': '',
                    'cookieString': '',
                    'captchaValidate': '',
                    'captchaId': 'a17cc715e78a4afc8c43cd85da9d7254',
                    'target': 'https://dc.oilchem.net/page/#/index',
                    'check': True,
                    'persist': True},
  'suggestedCron': '',
  'executionMode': 'SINGLE',
  'idempotencyPolicy': 'IDEMPOTENT',
  'resourceRequirements': {},
  'requiredCapabilities': {'browser': False},
  'runtimeMode': 'SHARED_ENV_ISOLATED',
  'taskGroup': 'oilchem',
  'taskMaxConcurrency': 1,
  'groupMaxConcurrency': 2,
  'exclusiveMode': False,
  'ioClass': 'NORMAL',
  'shmSizeMb': 64,
  'logLimitMb': 20,
  'resourceLocks': [],
  'secretRefs': ['oilchem_account'],
  'entryModule': 'spiders.oilchem.login',
  'entryFunction': 'run',
  'sourceFile': 'spiders/oilchem/login.py'},
 {'definitionKey': 'system_health',
  'taskName': '系统健康检查',
  'defaultParams': {'message': 'health check passed'},
  'suggestedCron': '',
  'executionMode': 'SINGLE',
  'idempotencyPolicy': 'IDEMPOTENT',
  'resourceRequirements': {},
  'requiredCapabilities': {'browser': False},
  'runtimeMode': 'SHARED_ENV_ISOLATED',
  'taskGroup': 'system',
  'taskMaxConcurrency': 1,
  'groupMaxConcurrency': 4,
  'exclusiveMode': False,
  'ioClass': 'LOW',
  'shmSizeMb': 64,
  'logLimitMb': 20,
  'resourceLocks': [],
  'secretRefs': [],
  'entryModule': 'spiders.system.health',
  'entryFunction': 'run',
  'sourceFile': 'spiders/system/health.py'}]
