[grop:spiders]
programs = sch
[program:sch]
command = /data/.virtualenvs/scraperApi/bin/python /data/ROOT/ulike-overseas-scraper/sch.py
directory = /data/ROOT/ulike-overseas-scraper
autostart = true     ; 在 supervisord 启动的时候也自动启动
startsecs = 5        ;启动5 秒后没有异常退出，就当作已经正常启动了
autorestart = true   ; 程序异常退出后自动重启
startretries = 3     ; 启动失败自动重试次数，默认是 3
user = root        ; 用哪个用户启动,要与当前用户保持一致
redirect_stderr = true  ; 把 stderr 重定向到 stdout，默认 false
stdout_logfile_maxbytes = 20MB  ; stdout 日志文件大小，默认 50MB
stdout_logfile_backups = 20     ; stdout 日志文件备份数stdout 日志文件，需要注意当指定目录不存在时无法正常启动，所以需要手动创建目supervisord 会自动创建日志文件）
stdout_logfile = /data/ROOT/ulike-overseas-scraper/logs/sch_info.log
stderr_logfile = /data/ROOT/ulike-overseas-scraper/logs/sch_error.log
loglevel = info
environment = SPIDERDEV=3 ;environment=SPIDERDEV=2,A=3 设置环境变量
# /usr/bin/python3 /usr/bin/supervisord -n -c /etc/supervisor/supervisord.conf

[program:run_task]
command = /data/.virtualenvs/scraperApi/bin/python /data/ROOT/ulike-overseas-scraper/start.py
directory = /data/ROOT/ulike-overseas-scraper
autostart = true     ; 在 supervisord 启动的时候也自动启动
startsecs = 5        ;启动5 秒后没有异常退出，就当作已经正常启动了
autorestart = true   ; 程序异常退出后自动重启
startretries = 3     ; 启动失败自动重试次数，默认是 3
user = ulike        ; 用哪个用户启动,要与当前用户保持一致
redirect_stderr = true  ; 把 stderr 重定向到 stdout，默认 false
stdout_logfile_maxbytes = 20MB  ; stdout 日志文件大小，默认 50MB
stdout_logfile_backups = 20     ; stdout 日志文件备份数stdout 日志文件，需要注意当指定目录不存在时无法正常启动，所以需要手动创建目supervisord 会自动创建日志文件）
stdout_logfile = /data/ROOT/ulike-overseas-scraper/logs/run_task_info.log
stderr_logfile = /data/ROOT/ulike-overseas-scraper/logs/run_task_error.log
loglevel = info
environment = SPIDERDEV=3 ;environment=SPIDERDEV=2,A=3 设置环境变量


[program:web-admin]
directory = /data/ROOT/task-master-backend
command = /data/.virtualenvs/task-admin/bin/gunicorn -c conf.py app:app
autostart = true
startsecs = 5
autorestart = true
startretries = 3
user = ulike
redirect_stderr = true
stdout_logfile_maxbytes = 20MB
stdout_logfile_backups = 20
stdout_logfile = /data/ROOT/task-master-backend/gunicorn_info.log
stderr_logfile = /data/ROOT/task-master-backend/gunicorn_error.log
loglevel = info


[program:agent_system_app]
command = /data/.virtualenvs/agent_system/bin/gunicorn -c conf.py api.main:app
directory = /data/ROOT/agent-system
autostart = true
startsecs = 5
autorestart = true
startretries = 3
user = ulike
redirect_stderr = true
stdout_logfile_maxbytes = 20MB
stdout_logfile_backups = 20
stdout_logfile = /data/ROOT/agent-system/logs/agent_system.log
stderr_logfile = /data/ROOT/agent-system/logs/agent_system-error.log
loglevel = info



[program:agent_system_worker]
command = /data/.virtualenvs/agent_system/bin/python /data/ROOT/agent-system/run_worker.py
directory = /data/ROOT/agent-system
autostart = true
startsecs = 5
autorestart = true
startretries = 3
user = ulike
redirect_stderr = true
stdout_logfile_maxbytes = 20MB
stdout_logfile_backups = 20
stdout_logfile = /data/ROOT/agent-system/logs/agent_system.log
stderr_logfile = /data/ROOT/agent-system/logs/agent_system_error.log
loglevel = info


[program:scheduler]
command = /data/.virtualenvs/scraperApi/bin/python /data/ROOT/ulike-overseas-scraper/scheduler.py
directory = /data/ROOT/ulike-overseas-scraper
autostart = true
startsecs = 5
autorestart = true
startretries = 3
user = ulike
redirect_stderr = true
stdout_logfile_maxbytes = 20MB
stdout_logfile_backups = 20
stdout_logfile = /data/ROOT/ulike-overseas-scraper/logs/scheduler.log
stderr_logfile = /data/ROOT/ulike-overseas-scraper/logs/scheduler_error.log
loglevel = info
environment = SPIDERDEV=3
stopsignal = TERM
stopasgroup = true
killasgroup = true
stopwaitsecs = 3000